pipeline {
  agent {
    kubernetes {
      defaultContainer 'python'
      showRawYaml false
      yaml """---
apiVersion: "v1"
kind: "Pod"
spec:
  containers:
  - name: jnlp
  - name: python
    image: ${python_image}
    command:
    - cat
    tty: true
"""
    }
  }

  stages {
    stage('Demo') {
      steps {
        sh 'python --version'
      }
    }
  }
}
