library identifier: 'my-library@master', changelog: false, retriever: modernSCM([$class: 'GitSCMSource', credentialsId: 'github', remote: 'git@github.com:ryecarrigan/pipeline-libraries.git'])

podTemplate {
  node(POD_LABEL) {
    stage('Build') {
      echo "Building from ${github_repo}"
    }

    stage('Deploy') {
      echo "Deploying to ${environment}"
    }
  }
}
