pipeline {
  agent {
    kubernetes true
  }

  stages {
    stage('Build') {
      steps {
        echo 'mvn package'
      }
    }

    stage('Deploy') {
      steps {
        echo "Deploy to ${environment}"
        echo 'mvn deploy'
      }
    }
  }
}
