pipeline {
  agent {
    kubernetes {
      defaultContainer 'maven'
      showRawYaml false
      yaml """---
apiVersion: "v1"
kind: "Pod"
spec:
  containers:
  - name: jnlp
  - name: maven
    image: ${maven_image}
    command:
    - cat
    tty: true
"""
    }
  }

  stages {
    stage('Build') {
      steps {
        echo 'Build stage'
      }
    }

    stage('Verify') {
      steps {
        echo 'Verify stage'
      }
    }

    stage('Test') {
      steps {
        echo 'Test stage'
      }
    }

    stage('Deploy') {
      steps {
        echo 'Deploy stage'
      }
    }
  }
}
