pipeline {
  agent {
    kubernetes {
      defaultContainer 'maven'
      yaml """---
apiVersion: "v1"
kind: "Pod"
spec:
  containers:
  - name: jnlp
  - name: maven
    image: ${maven_image}
    command:
    - cat
    tty: true
"""
    }
  }

  stages {
    stage('Build') {
      steps {
        doBuild()
      }
    }

    stage('Verify') {
      steps {
        doVerify()
      }
    }

    stage('Unit Tests') {
      steps {
        doUnitTests()
      }
    }

    stage('Integration Tests') {
      steps {
        doIntegrationTests()
      }
    }

    stage('Deploy') {
      steps {
        doDeploy()
      }
    }
  }
}
