pipeline {
  agent {
    kubernetes true
  }

  stages {
    stage('Build') {
      steps {
        echo 'npm install'
      }
    }

    stage('Test') {
      steps {
        echo 'npm test'
      }
    }

    stage('Deploy') {
      steps {
        echo 'npm publish'
      }
    }
  }
}
